name: Aprendendo Artefatos

on: 
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * *'

  push:
    branches:
      - 'feature/**' 
    paths:
      - 'src/**'    
      - '!src/docs/**' 

jobs:
  job_gerador:
    name: O Produtor de Artefatos
    runs-on: ubuntu-latest
    steps:
      # Passo 2 da Etapa 3: Simulando a build
      - name: Simular construção do projeto
        run: |
          mkdir saida_build
          echo "Relatório de Performance: 100%" > saida_build/relatorio1.txt
          echo "Relatório de Segurança: OK" > saida_build/relatorio2.txt

      # Passo 3 e 4 da Etapa 3: Upload oficial
      - name: Salvar relatórios no servidor
        uses: actions/upload-artifact@v4
        with:
          name: meus-relatorios-oficiais
          path: saida_build/

  job_auditoria:
    name: O Consumidor de Artefatos
    runs-on: ubuntu-latest
    needs: [job_gerador] # Regra 1 da Etapa 4: Aguarda o anterior
    steps:
      # Passo 2 da Etapa 4: Download oficial
      - name: Baixar pacote de relatórios
        uses: actions/download-artifact@v4
        with:
          name: meus-relatorios-oficiais

      # Passo 3 da Etapa 4: Prova de sobrevivência
      - name: Validar arquivos sobreviventes
        run: |
          ls -R
          cat relatorio1.txt